name: Build Docker Image

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  prebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Get GITHUB_REF_NAME
        run: sed "s/\//_/" <<< $GITHUB_REF_NAME
      - name: Get GITHUB_ACTOR
        run: echo "$GITHUB_ACTOR"
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag counter:$(sed "s/\//_/" <<< $GITHUB_REF_NAME)
  secret-test:
    runs-on: ubuntu-latest
    steps:
    - name: Use secret of $GITHUB_REPOSITORY
      run: echo "$secret.MY_SECRET_KEY"
